---
language: node_js
sudo: false
dist: trusty
node_js:
  - "10"

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    - JOBS=1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

before_script:
  - ember version
  - yarn list | grep ember-source

notifications:
  email: false

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

jobs:
  fail_fast: true

  include:
    - stage: test
      env: NAME=test
      script: yarn test

    - stage: test with separate build
      env: NAME=test with separate build
      script: yarn test:separate-build

    - stage: additional tests
      env: NAME=floating dependencies
      install: yarn install --no-lockfile --non-interactive
      script: yarn test
    - env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - env: EMBER_TRY_SCENARIO=ember-lts-3.8
    - env: EMBER_TRY_SCENARIO=ember-lts-3.12
    - env: EMBER_TRY_SCENARIO=fastboot-1.2
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary

    - stage: deploy
      if: (branch = master OR tag IS present) AND type = push
      env: NAME=deploy
      script: node_modules/.bin/ember deploy production

  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
